### ISSUE TITLE
Understanding Broccoli-istanbul

### ISSUE THREAD

**Issue by stffrd** [marcelerz/broccoli-istanbul#2]
Hello!

I've been playing around with webpack/istanbul/mocha/chai and I'm just all turned around trying to figure out how I'd implement this in my testing!

1) Do I need a brocfile for this?
2) Is this something I can include in my test.js like so:

```
var Browser = require('zombie');
var chai = require('chai'),
           expect = chai.expect;
var IstanbulCompiler = require('broccoli-istanbul');
var appJs = IstanbulCompiler(['../modules/vendor.js'], 'test/test.js', 'output/test.js');
```

 I'm wondering

1) What's the purpose of caching the compiler in appJs?
2) Why doesn't running my `istanbul cover node_modules/mocha/bin/_mocha -- -R spec` seem to work with this? I can understand that it's probably not going to work out of the box, but I also don't know what else to try, so I thought I'd test my luck at pinging you!

I guess I'm just confused about the workflow here.. Would it be better for me to just follow along with a brocfile tutorial?

**Comment by marcelerz** [comment]
HI!

It looks like you want to run tests on JavaScript code that is "server-side". The broccoli-instanbul package is only helpful to instrument code that will be executed in the browser to collect it there. You can collect the data there through for example Selenium or PhantomJs evaluation.

However, if you want to run tests in Node on the "server-side", which I think you want to do, you should use Istanbul directly; whenever you require a js-file, Istanbul would instrument it automatically.

For that, run `istanbul cover -- node_modules/mocha/bin/_mocha -R spec`. You had the `--` in the wrong place. I usually use it like this: https://github.com/yahoo/blink-diff/blob/master/package.json#L32

I hope that helps.

**Comment by stffrd** [comment]
I really appreciate it! :). KEEP FIGHTING THE GOOD FIGHT, SIR.  :+1:
